import json
from pathlib import Path
import numpy as np

report_file = Path('sr_mappo/results/sr_mappo_report_metrics.json')
with open(report_file) as f:
    data = json.load(f)

sr_mappo = data.get('sr_mappo', {})
greedy = data.get('selected_baseline', {})

print('=== ACTUAL PERFORMANCE COMPARISON ===')
print()
print('Load 5.0 - Light Load:')
print(f'  MAPPO Admission:  {sr_mappo.get("urllc_admission", [0])[0]:.4f}')
print(f'  Greedy Admission: {greedy.get("urllc_admission", [0])[0]:.4f}')
print()
print('Load 10.0:')
print(f'  MAPPO Admission:  {sr_mappo.get("urllc_admission", [0])[1]:.4f}')
print(f'  Greedy Admission: {greedy.get("urllc_admission", [0])[1]:.4f}')
print()
print('Load 15.0:')
print(f'  MAPPO Admission:  {sr_mappo.get("urllc_admission", [0])[2]:.4f}')
print(f'  Greedy Admission: {greedy.get("urllc_admission", [0])[2]:.4f}')
print()
print('Load 20.0:')
print(f'  MAPPO Admission:  {sr_mappo.get("urllc_admission", [0])[3]:.4f}')
print(f'  Greedy Admission: {greedy.get("urllc_admission", [0])[3]:.4f}')
print()
print('Load 25.0 - Heavy Load:')
print(f'  MAPPO Admission:  {sr_mappo.get("urllc_admission", [0])[4]:.4f} ← 74.6%')
print(f'  Greedy Admission: {greedy.get("urllc_admission", [0])[4]:.4f} ← 43.5%')
print()
print('Absolute difference at load 25.0: {:.2f}%'.format(
    (float(sr_mappo.get("urllc_admission", [0])[4]) - float(greedy.get("urllc_admission", [0])[4])) * 100
))
print()

print('=== eMBB THROUGHPUT TRADEOFF ===')
print()
print('Load 5.0:')
print(f'  MAPPO eMBB:  {sr_mappo.get("embb_rate", [0])[0] / 1e6:.2f} Mbps')
print(f'  Greedy eMBB: {greedy.get("embb_rate", [0])[0] / 1e6:.2f} Mbps')
print()
print('Load 25.0:')
print(f'  MAPPO eMBB:  {sr_mappo.get("embb_rate", [0])[4] / 1e6:.2f} Mbps')
print(f'  Greedy eMBB: {greedy.get("embb_rate", [0])[4] / 1e6:.2f} Mbps')
print()
print('Admission vs eMBB Tradeoff at high load:')
print(f'  ΔAdmission = +{(float(sr_mappo.get("urllc_admission", [0])[4]) - float(greedy.get("urllc_admission", [0])[4])) * 100:.1f}%')
print(f'  ΔeMBB = {(float(sr_mappo.get("embb_rate", [0])[4]) - float(greedy.get("embb_rate", [0])[4])) / 1e6:.2f} Mbps')
print()

print('=== WHY GRAPHS LOOK SIMILAR ===')
print()
print('The graphs likely show:')
print('  1. Load range 5-15: Both methods perform similarly (light to moderate load)')
print('  2. Load range 20-25: MAPPO switches strategy')
print('     - MAPPO: Prioritizes admission (+30% over greedy)')
print('     - MAPPO: Sacrifices some eMBB throughput (-2.9 Mbps)')
print()
print('  This IS a legitimate policy divergence!')
print('  The overlap you see might be due to:')
print('    - Graph scale (both achieve similar KPI values)')
print('    - Evaluation noise (6 episodes per load)')
print('    - Visual overlap at lower loads masking high-load difference')
